comment:
  require_changes: yes

coverage:
  status:
    project:
      default:
        target: 100
        threshold: null
        base: auto
        branches: null
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
    patch:
      default:
        target: 100
        threshold: null
        base: auto
        branches: null
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
