name: Build & Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run lint
      uses: ScaCap/action-ktlint@v1.0
      with:
        github_token: ${{ secrets.github_token }}
        reporter: github-pr-review
    - name: Build & Test
      run: ./gradlew build test
    - name: Upload coverage to Codecov  
      uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{secrets.CODECOV_TOKEN}}
